version: "3.8"
services:
  postgres:
    image: postgres:14
    container_name: postgres-14
    environment:
      - POSTGRES_USER=dev_admin
      - POSTGRES_PASSWORD=dev_admin
      - POSTGRES_DB=test_db
    ports:
      - "5432:5432"